/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as AuthAtividadeRouteImport } from './routes/_auth/atividade'
import { Route as AuthCarrinhoRouteImport } from './routes/_auth/carrinho'
import { Route as AuthCarteirasRouteImport } from './routes/_auth/carteiras'
import { Route as AuthListaDeInteresseRouteImport } from './routes/_auth/lista-de-interesse'
import { Route as AuthPagamentoRouteImport } from './routes/_auth/pagamento'
import { Route as AuthPerfilRouteImport } from './routes/_auth/perfil'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as AuthConfirmacaoOrderIdRouteImport } from './routes/_auth/confirmacao.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAtividadeRoute = AuthAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCarrinhoRoute = AuthCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCarteirasRoute = AuthCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListaDeInteresseRoute = AuthListaDeInteresseRouteImport.update({
  id: '/lista-de-interesse',
  path: '/lista-de-interesse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagamentoRoute = AuthPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmacaoOrderIdRoute = AuthConfirmacaoOrderIdRouteImport.update({
  id: '/confirmacao/$orderId',
  path: '/confirmacao/$orderId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/atividade': typeof AuthAtividadeRoute
  '/carrinho': typeof AuthCarrinhoRoute
  '/carteiras': typeof AuthCarteirasRoute
  '/lista-de-interesse': typeof AuthListaDeInteresseRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/confirmacao/$orderId': typeof AuthConfirmacaoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/atividade': typeof AuthAtividadeRoute
  '/carrinho': typeof AuthCarrinhoRoute
  '/carteiras': typeof AuthCarteirasRoute
  '/lista-de-interesse': typeof AuthListaDeInteresseRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/confirmacao/$orderId': typeof AuthConfirmacaoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/_auth/atividade': typeof AuthAtividadeRoute
  '/_auth/carrinho': typeof AuthCarrinhoRoute
  '/_auth/carteiras': typeof AuthCarteirasRoute
  '/_auth/lista-de-interesse': typeof AuthListaDeInteresseRoute
  '/_auth/pagamento': typeof AuthPagamentoRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/_auth/confirmacao/$orderId': typeof AuthConfirmacaoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/atividade'
    | '/carrinho'
    | '/carteiras'
    | '/lista-de-interesse'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/confirmacao/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/atividade'
    | '/carrinho'
    | '/carteiras'
    | '/lista-de-interesse'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/confirmacao/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/aprenda'
    | '/cadastro'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/_auth/atividade'
    | '/_auth/carrinho'
    | '/_auth/carteiras'
    | '/_auth/lista-de-interesse'
    | '/_auth/pagamento'
    | '/_auth/perfil'
    | '/nfts/$nftId'
    | '/_auth/confirmacao/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AprendaRoute: typeof AprendaRoute
  CadastroRoute: typeof CadastroRoute
  CriadoresRoute: typeof CriadoresRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/atividade': {
      id: '/_auth/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthAtividadeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/carrinho': {
      id: '/_auth/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthCarrinhoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/carteiras': {
      id: '/_auth/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof AuthCarteirasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lista-de-interesse': {
      id: '/_auth/lista-de-interesse'
      path: '/lista-de-interesse'
      fullPath: '/lista-de-interesse'
      preLoaderRoute: typeof AuthListaDeInteresseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pagamento': {
      id: '/_auth/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthPagamentoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/confirmacao/$orderId': {
      id: '/_auth/confirmacao/$orderId'
      path: '/confirmacao/$orderId'
      fullPath: '/confirmacao/$orderId'
      preLoaderRoute: typeof AuthConfirmacaoOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAtividadeRoute: typeof AuthAtividadeRoute
  AuthCarrinhoRoute: typeof AuthCarrinhoRoute
  AuthCarteirasRoute: typeof AuthCarteirasRoute
  AuthListaDeInteresseRoute: typeof AuthListaDeInteresseRoute
  AuthPagamentoRoute: typeof AuthPagamentoRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthConfirmacaoOrderIdRoute: typeof AuthConfirmacaoOrderIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAtividadeRoute: AuthAtividadeRoute,
  AuthCarrinhoRoute: AuthCarrinhoRoute,
  AuthCarteirasRoute: AuthCarteirasRoute,
  AuthListaDeInteresseRoute: AuthListaDeInteresseRoute,
  AuthPagamentoRoute: AuthPagamentoRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthConfirmacaoOrderIdRoute: AuthConfirmacaoOrderIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AprendaRoute: AprendaRoute,
  CadastroRoute: CadastroRoute,
  CriadoresRoute: CriadoresRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  NftsNftIdRoute: NftsNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
